import chalk from 'chalk';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import Pokemon from '../models/pokemon.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
/** @type {Object<string, string>} */
const emojis = JSON.parse(readFileSync(join(__dirname, '../../emojis.json'), 'utf8'));


export default async function seedPOR() {
  await Pokemon.bulkCreate([
    {
      name: 'Spinarak',
      id: 'POR001',
      expansion: 'Perfect Order',
      number: '001/088',
      rarity: `${emojis.CC} Common`,
      hp: 60,
      type: emojis.grass,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It spins a web using fine yet durable thread.\n' +
             'It then waits patiently for prey to be trapped.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'Katsunori Sato',
      pokedex: '0167',
      retreat: 1,
    },
    {
      name: 'Ariados',
      id: 'POR002',
      expansion: 'Perfect Order',
      number: '002/088',
      rarity: `${emojis.CC} Common`,
      hp: 110,
      type: emojis.grass,
      stage: 'Stage 1',
      evolvesFrom: 'Spinarak',
      blurb: 'It spins string not only from its rear but also from\n' +
             'its mouth. It\'s hard to tell which end is which.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'svlt',
      pokedex: '0168',
      retreat: 1,
    },
    {
      name: 'Shaymin',
      id: 'POR003',
      expansion: 'Perfect Order',
      number: '003/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 70,
      type: emojis.grass,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It can dissolve toxins in the air to instantly transform\n' +
             'ruined land into a lush field of flowers.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'saino misaki',
      pokedex: '0492',
      retreat: 0,
    },
    {
      name: 'Snivy',
      id: 'POR004',
      expansion: 'Perfect Order',
      number: '004/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.grass,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It prefers to avoid groups. In its day-to-day\n' +
             'life, it dexterously controls its vines to\n' +
             'compensate for its short arms.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'Narumi Sato',
      pokedex: '0495',
      retreat: 0,
    },
    {
      name: 'Servine',
      id: 'POR005',
      expansion: 'Perfect Order',
      number: '005/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.grass,
      stage: 'Stage 1',
      evolvesFrom: 'Snivy',
      blurb: 'Servine\'s one weakness is its inflated sense\n' +
             'of pride. It takes a while for Servine to be\n' +
             'able to cooperate with other Pokémon.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'Kurata So',
      pokedex: '0496',
      retreat: 1,
    },
    {
      name: 'Serperior',
      id: 'POR006',
      expansion: 'Perfect Order',
      number: '006/088',
      rarity: `${emojis.RR} Rare`,
      hp: 160,
      type: emojis.grass,
      stage: 'Stage 2',
      evolvesFrom: 'Servine',
      blurb: 'An intimidating gaze and majestic\n' +
             'appearance have caused this Pokémon to\n' +
             'be known as the Lord of the Forest',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'kodama',
      pokedex: '0497',
      retreat: 2,
    },
    {
      name: 'Scatterbug',
      id: 'POR007',
      expansion: 'Perfect Order',
      number: '007/088',
      rarity: `${emojis.CC} Common`,
      hp: 40,
      type: emojis.grass,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'The powder that covers its body regulates its\n' +
             'temperature, so it can live in any region or climate.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'OKACHEKE',
      pokedex: '0664',
      retreat: 1,
    },
    {
      name: 'Spewpa',
      id: 'POR008',
      expansion: 'Perfect Order',
      number: '008/088',
      rarity: `${emojis.CC} Common`,
      hp: 80,
      type: emojis.grass,
      stage: 'Stage 1',
      evolvesFrom: 'Scatterbug',
      blurb: 'It lives hidden within thicket shadows. When\n' +
             'predators attack, it bristles the fur covering\n' +
             'its body in an effort to threaten them.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'Ounishi',
      pokedex: '0665',
      retreat: 3,
    },
    {
      name: 'Vivillon',
      id: 'POR009',
      expansion: 'Perfect Order',
      number: '009/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 120,
      type: emojis.grass,
      stage: 'Stage 2',
      evolvesFrom: 'Spewpa',
      blurb: 'The patterns on this Pokémon depend on the\n' +
             'climate and topography of the land it was born in.\n' +
             'This form is from lands where flowers bloom.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'mingo',
      pokedex: '0666',
      retreat: 1,
    },
    {
      name: 'Rowlet',
      id: 'POR010',
      expansion: 'Perfect Order',
      number: '010/088',
      rarity: `${emojis.CC} Common`,
      hp: 80,
      type: emojis.grass,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It feels relaxed in tight, dark places and\n' +
             'has been known to nestle into its Trainer\'s\n' +
             'bag or the front of their jacket.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'Atsuya Uki',
      pokedex: '0722',
      retreat: 2,
    },
    {
      name: 'Dartrix',
      id: 'POR011',
      expansion: 'Perfect Order',
      number: '011/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.grass,
      stage: 'Stage 1',
      evolvesFrom: 'Rowlet',
      blurb: 'It throws sharp feathers called blade quills\n' +
             'at enemies or prey. It seldom misses.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'aspara',
      pokedex: '0723',
      retreat: 2,
    },
    {
      name: 'Decidueye ex',
      id: 'POR012',
      expansion: 'Perfect Order',
      number: '012/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 320,
      type: emojis.grass,
      stage: 'Stage 2',
      evolvesFrom: 'Dartrix',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'aky CG Works',
      pokedex: '0724',
      retreat: 2,
    },
    {
      name: 'Fletchinder',
      id: 'POR013',
      expansion: 'Perfect Order',
      number: '013/088',
      rarity: `${emojis.CC} Common`,
      hp: 90,
      type: emojis.fire,
      stage: 'Stage 1',
      evolvesFrom: 'Fletchling',
      blurb: 'The hotter the flame sac in its belly, the faster it can\n' +
             'fly, but it takes some time to get the fire going.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'Sumiyoshi Kizuki',
      pokedex: '0662',
      retreat: 1,
    },
    {
      name: 'Talonflame',
      id: 'POR014',
      expansion: 'Perfect Order',
      number: '014/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 150,
      type: emojis.fire,
      stage: 'Stage 2',
      evolvesFrom: 'Fletchinder',
      blurb: 'In the fever of an exciting battle, it showers embers\n' +
             'from the gaps between its feathers as it flies.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'Shinji Kanda',
      pokedex: '0663',
      retreat: 1,
    },
    {
      name: 'Salandit',
      id: 'POR015',
      expansion: 'Perfect Order',
      number: '015/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.fire,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Only female Salandit can produce gas laden\n' +
             'with pheromones. Males entranced by this\n' +
             'gas will do whatever the females tell them.',
      regulation: 'J',
      weakness: `${emojis.water} × 2`,
      resistance: null,
      illustrators: 'Kazuhisa Uragami',
      pokedex: '0757',
      retreat: 1,
    },
    {
      name: 'Salazzle ex',
      id: 'POR016',
      expansion: 'Perfect Order',
      number: '016/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 260,
      type: emojis.fire,
      stage: 'Stage 1',
      evolvesFrom: 'Salandit',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.water} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0758',
      retreat: 1,
    },
    {
      name: 'Turtonator',
      id: 'POR017',
      expansion: 'Perfect Order',
      number: '017/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 120,
      type: emojis.fire,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Explosive substances coat the shell on its\n' +
             'back. Enemies that dare attack it will be\n' +
             'blown away by an immense detonation.',
      regulation: 'J',
      weakness: `${emojis.water} × 2`,
      resistance: null,
      illustrators: 'Hasuno',
      pokedex: '0776',
      retreat: 2,
    },
    {
      name: 'Seel',
      id: 'POR018',
      expansion: 'Perfect Order',
      number: '018/088',
      rarity: `${emojis.CC} Common`,
      hp: 80,
      type: emojis.water,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'The colder it gets, the better it feels.\n' +
             'It joyfully swims around oceans so cold\n' +
             'that they are filled with floating ice.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: 'Kanami Ogata',
      pokedex: '0086',
      retreat: 2,
    },
    {
      name: 'Dewgong',
      id: 'POR019',
      expansion: 'Perfect Order',
      number: '019/088',
      rarity: `${emojis.RR} Rare`,
      hp: 130,
      type: emojis.water,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It stores thermal energy in its body to fend off the\n' +
             'cold. It swims at eight knots even in frigid waters.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: 'Yoshioka',
      pokedex: '0087',
      retreat: 2,
    },
    {
      name: 'Staryu',
      id: 'POR020',
      expansion: 'Perfect Order',
      number: '020/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.water,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Even if its body is torn, it can regenerate as long\n' +
             'as the glowing central core remains intact.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: 'Takeshi Nakamura',
      pokedex: '0120',
      retreat: 1,
    },
    {
      name: 'Mega Starmie ex',
      id: 'POR021',
      expansion: 'Perfect Order',
      number: '021/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 330,
      type: emojis.water,
      stage: 'Stage 1',
      evolvesFrom: 'Staryu',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0121',
      retreat: 2,
    },
    {
      name: 'Lapras ex',
      id: 'POR022',
      expansion: 'Perfect Order',
      number: '022/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 210,
      type: emojis.water,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0131',
      retreat: 1,
    },
    {
      name: 'Amaura',
      id: 'POR023',
      expansion: 'Perfect Order',
      number: '023/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.water,
      stage: 'Stage 1',
      evolvesFrom: 'Antique Sail Fossil',
      blurb: 'This ancient Pokémon was restored from a part of its\n' +
             'body that had been frozen in ice for 100 million years.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Hitoshi Ariga',
      pokedex: '0698',
      retreat: 3,
    },
    {
      name: 'Aurorus',
      id: 'POR024',
      expansion: 'Perfect Order',
      number: '024/088',
      rarity: `${emojis.RR} Rare`,
      hp: 170,
      type: emojis.water,
      stage: 'Stage 2',
      evolvesFrom: 'Amaura',
      blurb: 'The diamond-shaped crystals on its body expel air\n' +
             'as cold as -240 degrees Fahrenheit, surrounding\n' +
             'its enemies and encasing them in ice.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'HACCAN',
      pokedex: '0699',
      retreat: 3,
    },
    {
      name: 'Volcanion',
      id: 'POR025',
      expansion: 'Perfect Order',
      number: '025/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 130,
      type: emojis.water,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It lets out billows of steam and disappears\n' +
             'into the dense fog. It\'s said to live in\n' +
             'mountains where humans do not tread.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: 'AKIRA EGAWA',
      pokedex: '0721',
      retreat: 3,
    },
    {
      name: 'Shinx',
      id: 'POR026',
      expansion: 'Perfect Order',
      number: '026/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.lightning,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'The extension and contraction of its muscles\n' +
             'generates electricity. Its fur glows when its in trouble.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Saboteri',
      pokedex: '0403',
      retreat: 1,
    },
    {
      name: 'Luxio',
      id: 'POR027',
      expansion: 'Perfect Order',
      number: '027/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 90,
      type: emojis.lightning,
      stage: 'Stage 1',
      evolvesFrom: 'Shinx',
      blurb: 'By gathering their tails together, they collectively\n' +
             'generate powerful electricity from their claws',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Atsuka Nishida',
      pokedex: '0404',
      retreat: 1,
    },
    {
      name: 'Luxray',
      id: 'POR028',
      expansion: 'Perfect Order',
      number: '028/088',
      rarity: `${emojis.RR} Rare`,
      hp: 150,
      type: emojis.lightning,
      stage: 'Stage 2',
      evolvesFrom: 'Luxio',
      blurb: 'Luxray\'s ability to see through objects comes\n' +
             'in handy when it\'s scouting for danger.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Taiga Kasai',
      pokedex: '0405',
      retreat: 0,
    },
    {
      name: 'Dedenne',
      id: 'POR029',
      expansion: 'Perfect Order',
      number: '029/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.lightning,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Its whiskers serve as antennas. By sending and\n' +
             'receiving electrical waves, it can communicate\n' +
             'with others over vast distances.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'sowsow',
      pokedex: '0702',
      retreat: 1,
    },
    {
      name: 'Clefairy',
      id: 'POR030',
      expansion: 'Perfect Order',
      number: '030/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.psychic,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'The moonlight that it stores in the wings on its back\n' +
             'apparently gives it the ability to float in midair.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Natsumi Yoshida',
      pokedex: '0035',
      retreat: 1,
    },
    {
      name: 'Mega Clefable ex',
      id: 'POR031',
      expansion: 'Perfect Order',
      number: '031/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 320,
      type: emojis.psychic,
      stage: 'Stage 1',
      evolvesFrom: 'Clefairy',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'aky CG Works',
      pokedex: '0036',
      retreat: 1,
    },
    {
      name: 'Mawile',
      id: 'POR032',
      expansion: 'Perfect Order',
      number: '032/088',
      rarity: `${emojis.CC} Common`,
      hp: 110,
      type: emojis.psychic,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Attached to its head is a huge set of jaws formed\n' +
             'by horns. It can chew through iron beams.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'OKACHEKE',
      pokedex: '0303',
      retreat: 2,
    },
    {
      name: 'Espurr',
      id: 'POR033',
      expansion: 'Perfect Order',
      number: '033/088',
      rarity: `${emojis.CC} Common`,
      hp: 60,
      type: emojis.psychic,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It keeps its intense psychic power from leaking out by\n' +
             'using its ears to cover the organs emitting that power.',
      regulation: 'J',
      weakness: `${emojis.darkness} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'Terada Tera',
      pokedex: '0677',
      retreat: 1,
    },
    {
      name: 'Meowstic',
      id: 'POR034',
      expansion: 'Perfect Order',
      number: '034/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 100,
      type: emojis.psychic,
      stage: 'Stage 1',
      evolvesFrom: 'Espurr',
      blurb: 'Females are a bit more selfish and aggressive\n' +
             'than males. If they don\'t get what they want, they\n' +
             'will torment you with their psychic abilities.',
      regulation: 'J',
      weakness: `${emojis.darkness} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'Kannnu',
      pokedex: '0678',
      retreat: 1,
    },
    {
      name: 'Spritzee',
      id: 'POR035',
      expansion: 'Perfect Order',
      number: '035/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.psychic,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'In the past, rather than using perfume,\n' +
             'royal ladies carried a Spritzee that\n' +
             'would waft a fragrance they liked.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Pani Kobayashi',
      pokedex: '0682',
      retreat: 1,
    },
    {
      name: 'Aromatisse',
      id: 'POR036',
      expansion: 'Perfect Order',
      number: '036/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 120,
      type: emojis.psychic,
      stage: 'Stage 1',
      evolvesFrom: 'Spritzee',
      blurb: 'Its scent is so overpowering that, unless they\n' +
             'happen to really enjoy the smell, Trainers will\n' +
             'have a hard time walking alongside it.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Mori Yuu',
      pokedex: '0683',
      retreat: 1,
    },
    {
      name: 'Nosepass',
      id: 'POR037',
      expansion: 'Perfect Order',
      number: '037/088',
      rarity: `${emojis.CC} Common`,
      hp: 90,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'When endangered, it may protect itself\n' +
             'by increasing its magnetism and drawing\n' +
             'nearby iron objects to its body.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Jerky',
      pokedex: '0299',
      retreat: 3,
    },
    {
      name: 'Probopass',
      id: 'POR038',
      expansion: 'Perfect Order',
      number: '038/088',
      rarity: `${emojis.CC} Common`,
      hp: 140,
      type: emojis.fighting,
      stage: 'Stage 1',
      evolvesFrom: 'Nosepass',
      blurb: 'Probopass radiates such a powerful magnetic\n' +
             'field that nearby electrical appliances are\n' +
             'rendered useless while it\'s around.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Nurikabe',
      pokedex: '0476',
      retreat: 3,
    },
    {
      name: 'Hippopotas',
      id: 'POR039',
      expansion: 'Perfect Order',
      number: '039/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It enshrouds itself with sand to protect itself\n' +
             'from germs. It does not enjoy getting wet.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Kagemaru Himeno',
      pokedex: '0449',
      retreat: 4,
    },
    {
      name: 'Hippowdon',
      id: 'POR040',
      expansion: 'Perfect Order',
      number: '040/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 150,
      type: emojis.fighting,
      stage: 'Stage 1',
      evolvesFrom: 'Hippopotas',
      blurb: 'It blasts internally stored sand from ports on its\n' +
             'body to create a towering twister for attack.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Souichirou Gunjima',
      pokedex: '0450',
      retreat: 4,
    },
    {
      name: 'Landorus',
      id: 'POR041',
      expansion: 'Perfect Order',
      number: '041/088',
      rarity: `${emojis.RR} Rare`,
      hp: 120,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Lands visited by Landorus grant such bountiful crops\n' +
             'that it has been hailed as "The Guardian of the Fields."',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'aoki',
      pokedex: '0645',
      retreat: 1,
    },
    {
      name: 'Binacle',
      id: 'POR042',
      expansion: 'Perfect Order',
      number: '042/088',
      rarity: `${emojis.CC} Common`,
      hp: 80,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Two Binacle live together on one rock. When they\n' +
             'fight one of them will move to a different rock.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'nagimiso',
      pokedex: '0688',
      retreat: 2,
    },
    {
      name: 'Barbaracle',
      id: 'POR043',
      expansion: 'Perfect Order',
      number: '043/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 130,
      type: emojis.fighting,
      stage: 'Stage 1',
      evolvesFrom: 'Binacle',
      blurb: 'Barbaracle\'s legs and hands have minds of\n' +
             'their own, and they will move independently.\n' +
             'But they usually follow the head\'s orders.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Kazumasa Yasukuni',
      pokedex: '0689',
      retreat: 2,
    },
    {
      name: 'Tyrunt',
      id: 'POR044',
      expansion: 'Perfect Order',
      number: '044/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.fighting,
      stage: 'Stage 1',
      evolvesFrom: 'Antique Jaw Fossil',
      blurb: 'This Pokémon was restored from a fossil.\n' +
             'If something happens that it doesn\'t like,\n' +
             'it throws a tantrum and runs wild.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Tomoki Sone',
      pokedex: '0696',
      retreat: 3,
    },
    {
      name: 'Tyrantrum',
      id: 'POR045',
      expansion: 'Perfect Order',
      number: '045/088',
      rarity: `${emojis.RR} Rare`,
      hp: 180,
      type: emojis.fighting,
      stage: 'Stage 2',
      evolvesFrom: 'Tyrunt',
      blurb: 'This Pokémon behaved like a king 100 million\n' +
             '\n' +
             'years ago. Nothing could stop it.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Dsuke',
      pokedex: '0697',
      retreat: 3,
    },
    {
      name: 'Hawlucha',
      id: 'POR046',
      expansion: 'Perfect Order',
      number: '046/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'With its wings, it controls its position in the\n' +
             'air, It likes to attack from above, a maneuver\n' +
             'that is difficult to defend against.',
      regulation: 'J',
      weakness: `${emojis.psychic} × 2`,
      resistance: null,
      illustrators: 'osare',
      pokedex: '0701',
      retreat: 0,
    },
    {
      name: 'Mega Zygarde ex',
      id: 'POR047',
      expansion: 'Perfect Order',
      number: '047/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 310,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'takuyoa',
      pokedex: '0718',
      retreat: 2,
    },
    {
      name: 'Gastly',
      id: 'POR048',
      expansion: 'Perfect Order',
      number: '048/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.darkness,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It\'s born from gases. Anyone would faint if engulfed\n' +
             'by its gaseous body, which contains poison.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'MARINA Chikazawa',
      pokedex: '0092',
      retreat: 1,
    },
    {
      name: 'Haunter',
      id: 'POR049',
      expansion: 'Perfect Order',
      number: '049/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.darkness,
      stage: 'Stage 1',
      evolvesFrom: 'Gastly',
      blurb: 'It licks with its gaseous tongue to steal its victim\'s\n' +
             '\n' +
             'life force. It lurks in darkness, waiting for prey.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Kedamahadaitai Yawarakai',
      pokedex: '0093',
      retreat: 1,
    },
    {
      name: 'Gengar',
      id: 'POR050',
      expansion: 'Perfect Order',
      number: '050/088',
      rarity: `${emojis.RR} Rare`,
      hp: 130,
      type: emojis.darkness,
      stage: 'Stage 2',
      evolvesFrom: 'Haunter',
      blurb: 'It hides in shadows. It is said that in rooms\n' +
             'where Gengar is hiding, the temperature\n' +
             'drops by nearly 10 degrees Fahrenheit',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Masako Tomii',
      pokedex: '0094',
      retreat: 1,
    },
    {
      name: 'Skorupi',
      id: 'POR051',
      expansion: 'Perfect Order',
      number: '051/088',
      rarity: `${emojis.CC} Common`,
      hp: 80,
      type: emojis.darkness,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'After burrowing into the sand, it waits patiently\n' +
             'for prey to come near. This Pokémon and\n' +
             'Sizzlipede share common descent.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Aya Kusube',
      pokedex: '0451',
      retreat: 2,
    },
    {
      name: 'Drapion',
      id: 'POR052',
      expansion: 'Perfect Order',
      number: '052/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 140,
      type: emojis.darkness,
      stage: 'Stage 1',
      evolvesFrom: 'Skorupi',
      blurb: 'Its poison is potent, but it rarely sees use. This\n' +
             'Pokémon prefers to use physical force instead,\n' +
             'going on rampages with its car-crushing strength.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Nelnal',
      pokedex: '0452',
      retreat: 3,
    },
    {
      name: 'Yveltal ex',
      id: 'POR053',
      expansion: 'Perfect Order',
      number: '053/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 210,
      type: emojis.darkness,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: '5ban Graphics',
      pokedex: '0717',
      retreat: 1,
    },
    {
      name: 'Chien-Pao',
      id: 'POR054',
      expansion: 'Perfect Order',
      number: '054/088',
      rarity: `${emojis.RR} Rare`,
      hp: 120,
      type: emojis.darkness,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'The hatred of those who perished by the sword long\n' +
             '\n' +
             'ago has clad itself in snow and become a Pokémon.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Satoshi Ito',
      pokedex: '1002',
      retreat: 1,
    },
    {
      name: 'Mega Skarmory ex',
      id: 'POR055',
      expansion: 'Perfect Order',
      number: '055/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 260,
      type: emojis.metal,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: '5ban Graphics',
      pokedex: '0227',
      retreat: 0,
    },
    {
      name: 'Honedge',
      id: 'POR056',
      expansion: 'Perfect Order',
      number: '056/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.metal,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Apparently Honedge was born when a departed\n' +
             'spirit began inhabiting an ancient sword. It attaches\n' +
             'itself to people and drinks their life force.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: `${emojis.grass} − 30`,
      illustrators: 'Apios',
      pokedex: '0679',
      retreat: 2,
    },
    {
      name: 'Doublade',
      id: 'POR057',
      expansion: 'Perfect Order',
      number: '057/088',
      rarity: `${emojis.CC} Common`,
      hp: 100,
      type: emojis.metal,
      stage: 'Stage 1',
      evolvesFrom: 'Honedge',
      blurb: 'When Honedge evolves, it divides into two\n' +
             'swords that cooperate via telepathy to coordinate\n' +
             'attacks and slash their enemies to ribbons',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: `${emojis.grass} − 30`,
      illustrators: 'Kamome Shirahama',
      pokedex: '0680',
      retreat: 2,
    },
    {
      name: 'Aegislash',
      id: 'POR058',
      expansion: 'Perfect Order',
      number: '058/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 150,
      type: emojis.metal,
      stage: 'Stage 2',
      evolvesFrom: 'Doublade',
      blurb: 'This stance is dedicated to offense. It can\n' +
             'cleave any opponent with the strength\n' +
             'and weight of its steel blade.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: `${emojis.grass} − 30`,
      illustrators: 'Mitsuhiro Arita',
      pokedex: '0681',
      retreat: 3,
    },
    {
      name: 'Klefki',
      id: 'POR059',
      expansion: 'Perfect Order',
      number: '059/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.metal,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It never lets go of a key that it likes, so people give it\n' +
             'the keys to vaults and safes as a way to prevent crime.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: `${emojis.grass} − 30`,
      illustrators: 'MINAMINAMI Take',
      pokedex: '0707',
      retreat: 1,
    },
    {
      name: 'Rattata',
      id: 'POR060',
      expansion: 'Perfect Order',
      number: '060/088',
      rarity: `${emojis.CC} Common`,
      hp: 40,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Its incisors grow continuously throughout its\n' +
             'life. If its incisors get too long, this Pokémon\n' +
             'becomes unable to eat, and it starves to death.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Shinya Komatsu',
      pokedex: '0019',
      retreat: 1,
    },
    {
      name: 'Raticate',
      id: 'POR061',
      expansion: 'Perfect Order',
      number: '061/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 90,
      type: emojis.colorless,
      stage: 'Stage 1',
      evolvesFrom: 'Rattata',
      blurb: 'People say that it fled from its enemies\n' +
             'by using its small webbed hind feet to\n' +
             'swim from island to island in Alola.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Minahamu',
      pokedex: '0020',
      retreat: 1,
    },
    {
      name: 'Meowth ex',
      id: 'POR062',
      expansion: 'Perfect Order',
      number: '062/088',
      rarity: `${emojis.DR} Double Rare`,
      hp: 170,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0052',
      retreat: 1,
    },
    {
      name: 'Snorlax',
      id: 'POR063',
      expansion: 'Perfect Order',
      number: '063/088',
      rarity: `${emojis.CC} Common`,
      hp: 160,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Its stomach\'s digestive juices can dissolve\n' +
             'any kind of poison. Eating things off the\n' +
             'ground doesn\'t bother it at all.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Toshinao Aoki',
      pokedex: '0143',
      retreat: 4,
    },
    {
      name: 'Bunnelby',
      id: 'POR064',
      expansion: 'Perfect Order',
      number: '064/088',
      rarity: `${emojis.CC} Common`,
      hp: 70,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'They use their large ears to dig burrows. They\n' +
             'will dig the whole night through without rest.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'MINAMINAMI Take',
      pokedex: '0659',
      retreat: 1,
    },
    {
      name: 'Diggersby',
      id: 'POR065',
      expansion: 'Perfect Order',
      number: '065/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 150,
      type: emojis.colorless,
      stage: 'Stage 1',
      evolvesFrom: 'Bunnelby',
      blurb: 'With their powerful ears, they can heft\n' +
             'boulders of a ton or more with ease. They\n' +
             'can be a big help at construction sites.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Mousho',
      pokedex: '0660',
      retreat: 4,
    },
    {
      name: 'Fletchling',
      id: 'POR066',
      expansion: 'Perfect Order',
      number: '066/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: 60,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Despite the beauty of its lilting voice, it\'s\n' +
             'merciless to intruders that enter its territory.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'sowsow',
      pokedex: '0661',
      retreat: 1,
    },
    {
      name: 'Furfrou',
      id: 'POR067',
      expansion: 'Perfect Order',
      number: '067/088',
      rarity: `${emojis.CC} Common`,
      hp: 90,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Historically, in the Kalos region, these Pokémon\n' +
             'were the designated guardians of the king.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Teeziro',
      pokedex: '0676',
      retreat: 1,
    },
    {
      name: 'Antique Jaw Fossil',
      id: 'POR068',
      expansion: 'Perfect Order',
      number: '068/088',
      rarity: `${emojis.CC} Common`,
      hp: 60,
      type: 'Item',
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'AYUMI ODASHIMA',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Antique Sail Fossil',
      id: 'POR069',
      expansion: 'Perfect Order',
      number: '069/088',
      rarity: `${emojis.CC} Common`,
      hp: 60,
      type: 'Item',
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'AYUMI ODASHIMA',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Core Memory',
      id: 'POR070',
      expansion: 'Perfect Order',
      number: '070/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Pokémon Tool',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Toyste Beach',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Crushing Hammer',
      id: 'POR071',
      expansion: 'Perfect Order',
      number: '071/088',
      rarity: `${emojis.CC} Common`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Ayaka Yoshida',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Energy Search',
      id: 'POR072',
      expansion: 'Perfect Order',
      number: '072/088',
      rarity: `${emojis.CC} Common`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Toyste Beach',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Energy Swatter',
      id: 'POR073',
      expansion: 'Perfect Order',
      number: '073/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Toyste Beach',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Hole-Digging Shovel',
      id: 'POR074',
      expansion: 'Perfect Order',
      number: '074/088',
      rarity: `${emojis.CC} Common`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Toyste Beach',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Jacinthe',
      id: 'POR075',
      expansion: 'Perfect Order',
      number: '075/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Susumu Maeya',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Judge',
      id: 'POR076',
      expansion: 'Perfect Order',
      number: '076/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'kantaro',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Lumiose City',
      id: 'POR077',
      expansion: 'Perfect Order',
      number: '077/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Stadium',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'MARINA Chikazawa',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Lumiose Galette',
      id: 'POR078',
      expansion: 'Perfect Order',
      number: '078/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Naveen',
      id: 'POR079',
      expansion: 'Perfect Order',
      number: '079/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'DOM',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Poké Ball',
      id: 'POR080',
      expansion: 'Perfect Order',
      number: '080/088',
      rarity: `${emojis.CC} Common`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Studio Bora Inc.',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Poké Pad',
      id: 'POR081',
      expansion: 'Perfect Order',
      number: '081/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Studio Bora Inc.',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Pokémon Catcher',
      id: 'POR082',
      expansion: 'Perfect Order',
      number: '082/088',
      rarity: `${emojis.CC} Common`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Studio Bora Inc.',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Potion',
      id: 'POR083',
      expansion: 'Perfect Order',
      number: '083/088',
      rarity: `${emojis.CC} Common`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Ayaka Yoshida',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Rosa\'s Encouragement',
      id: 'POR084',
      expansion: 'Perfect Order',
      number: '084/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Atushi Furusawa',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Tarragon',
      id: 'POR085',
      expansion: 'Perfect Order',
      number: '085/088',
      rarity: `${emojis.UC} Uncommon`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Akira Komayama',
      pokedex: null,
      retreat: null,
    },
    {
      name: `Growing ${emojis.grass} Energy`,
      id: 'POR086',
      expansion: 'Perfect Order',
      number: '086/088',
      rarity: `${emojis.RR} Rare`,
      hp: null,
      type: 'Special Energy',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: null,
      pokedex: null,
      retreat: null,
    },
    {
      name: `Rocky ${emojis.fighting} Energy`,
      id: 'POR087',
      expansion: 'Perfect Order',
      number: '087/088',
      rarity: `${emojis.RR} Rare`,
      hp: null,
      type: 'Special Energy',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: null,
      pokedex: null,
      retreat: null,
    },
    {
      name: `Telepathic ${emojis.psychic} Energy`,
      id: 'POR088',
      expansion: 'Perfect Order',
      number: '088/088',
      rarity: `${emojis.RR} Rare`,
      hp: null,
      type: 'Special Energy',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: null,
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Spewpa',
      id: 'POR089',
      expansion: 'Perfect Order',
      number: '089/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 80,
      type: emojis.grass,
      stage: 'Stage 1',
      evolvesFrom: 'Scatterbug',
      blurb: 'It lives hidden within thicket shadows. When\n' +
             'predators attack, it bristles the fur covering\n' +
             'its body in an effort to threaten them.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'kamonabe',
      pokedex: '0665',
      retreat: 3,
    },
    {
      name: 'Rowlet',
      id: 'POR090',
      expansion: 'Perfect Order',
      number: '090/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 80,
      type: emojis.grass,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It feels relaxed in tight, dark places and\n' +
             'has been known to nestle into its Trainer\'s\n' +
             'bag or the front of their jacket.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: 'ryoma uratsuka',
      pokedex: '0722',
      retreat: 2,
    },
    {
      name: 'Talonflame',
      id: 'POR091',
      expansion: 'Perfect Order',
      number: '091/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 150,
      type: emojis.fire,
      stage: 'Stage 2',
      evolvesFrom: 'Fletchinder',
      blurb: 'In the fever of an exciting battle, it showers embers\n' +
             'from the gaps between its feathers as it flies.',
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'OKACHEKE',
      pokedex: '0663',
      retreat: 1,
    },
    {
      name: 'Aurorus',
      id: 'POR092',
      expansion: 'Perfect Order',
      number: '092/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 170,
      type: emojis.water,
      stage: 'Stage 2',
      evolvesFrom: 'Amaura',
      blurb: 'The diamond shaped crystals on its body expel air\n' +
             'as cold as −240 degrees Fahrenheit, surrounding\n' +
             'its enemies and encasing them in ice.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Masa',
      pokedex: '0699',
      retreat: 3,
    },
    {
      name: 'Dedenne',
      id: 'POR093',
      expansion: 'Perfect Order',
      number: '093/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 70,
      type: emojis.lightning,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'Its whiskers serve as antennas. By sending and\n' +
             'receiving electrical waves, it can communicate\n' +
             'with others over vast distances.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'HYOGONOSUKE',
      pokedex: '0702',
      retreat: 1,
    },
    {
      name: 'Clefairy',
      id: 'POR094',
      expansion: 'Perfect Order',
      number: '094/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 70,
      type: emojis.psychic,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'The moonlight that it stores in the wings on its back\n' +
             'apparently gives it the ability to float in midair.',
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Cona Nitanda',
      pokedex: '0035',
      retreat: 1,
    },
    {
      name: 'Espurr',
      id: 'POR095',
      expansion: 'Perfect Order',
      number: '095/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 60,
      type: emojis.psychic,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: 'It keeps its intense psychic power from leaking out by\n' +
             'using its ears to cover the organs emitting that power.',
      regulation: 'J',
      weakness: `${emojis.darkness} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: 'MINAMINAMI Take',
      pokedex: '0677',
      retreat: 1,
    },
    {
      name: 'Probopass',
      id: 'POR096',
      expansion: 'Perfect Order',
      number: '096/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 140,
      type: emojis.fighting,
      stage: 'Stage 1',
      evolvesFrom: 'Nosepass',
      blurb: 'Probopass radiates such a powertu magnetic\n' +
             'field that nearby electrical appliances are\n' +
             'rendered useless while it\'s around.',
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'Kinu Nishimura',
      pokedex: '0476',
      retreat: 3,
    },
    {
      name: 'Drapion',
      id: 'POR097',
      expansion: 'Perfect Order',
      number: '097/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 140,
      type: emojis.darkness,
      stage: 'Stage 1',
      evolvesFrom: 'Skorupi',
      blurb: 'Its poison is potent, but it rarely sees use. This\n' +
             'Pokémon prefers to use physical force instead,\n' +
             'going on rampages with its car-crushing strength.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'kawayoo',
      pokedex: '0452',
      retreat: 3,
    },
    {
      name: 'Doublade',
      id: 'POR098',
      expansion: 'Perfect Order',
      number: '098/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 100,
      type: emojis.metal,
      stage: 'Stage 1',
      evolvesFrom: 'Honedge',
      blurb: 'When Honedge evolves, it divides into two\n' +
             'swords that cooperate via telepathy to coordinate\n' +
             'attacks and slash their enemies to ribbons.',
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: `${emojis.grass} − 30`,
      illustrators: 'Anesaki Dynamic',
      pokedex: '0680',
      retreat: 2,
    },
    {
      name: 'Raticate',
      id: 'POR099',
      expansion: 'Perfect Order',
      number: '099/088',
      rarity: `${emojis.IR} Illustration Rare`,
      hp: 90,
      type: emojis.colorless,
      stage: 'Stage 1',
      evolvesFrom: 'Rattata',
      blurb: 'People say that it fled from its enemies\n' +
             'by using its small webbed hind feet to\n' +
             'swim from island to island in Alola.',
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Mina Nakai',
      pokedex: '0020',
      retreat: 1,
    },
    {
      name: 'Decidueye ex',
      id: 'POR100',
      expansion: 'Perfect Order',
      number: '100/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 320,
      type: emojis.grass,
      stage: 'Stage 2',
      evolvesFrom: 'Dartrix',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.fire} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0724',
      retreat: 2,
    },
    {
      name: 'Salazzle ex',
      id: 'POR101',
      expansion: 'Perfect Order',
      number: '101/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 260,
      type: emojis.fire,
      stage: 'Stage 1',
      evolvesFrom: 'Salandit',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.water} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0758',
      retreat: 1,
    },
    {
      name: 'Mega Starmie ex',
      id: 'POR102',
      expansion: 'Perfect Order',
      number: '102/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 330,
      type: emojis.water,
      stage: 'Stage 1',
      evolvesFrom: 'Staryu',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0121',
      retreat: 2,
    },
    {
      name: 'Mega Clefable ex',
      id: 'POR103',
      expansion: 'Perfect Order',
      number: '103/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 320,
      type: emojis.psychic,
      stage: 'Stage 1',
      evolvesFrom: 'Mega Clefable',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'aky CG Works',
      pokedex: '0036',
      retreat: 1,
    },
    {
      name: 'Mega Zygarde ex',
      id: 'POR104',
      expansion: 'Perfect Order',
      number: '104/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 310,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'takuyoa',
      pokedex: '0718',
      retreat: 2,
    },
    {
      name: 'Yveltal ex',
      id: 'POR105',
      expansion: 'Perfect Order',
      number: '105/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 210,
      type: emojis.darkness,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: '5ban Graphics',
      pokedex: '0717',
      retreat: 1,
    },
    {
      name: 'Mega Skarmory ex',
      id: 'POR106',
      expansion: 'Perfect Order',
      number: '106/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 260,
      type: emojis.metal,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: `${emojis.fighting} − 30`,
      illustrators: '5ban Graphics',
      pokedex: '0227',
      retreat: 0,
    },
    {
      name: 'Meowth',
      id: 'POR107',
      expansion: 'Perfect Order',
      number: '107/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: 170,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: '5ban Graphics',
      pokedex: '0052',
      retreat: 1,
    },
    {
      name: 'Energy Recycler',
      id: 'POR108',
      expansion: 'Perfect Order',
      number: '108/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Toyste Beach',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Forest of Vitality',
      id: 'POR109',
      expansion: 'Perfect Order',
      number: '109/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Stadium',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'AYUMI ODASHIMA',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Jacinthe',
      id: 'POR110',
      expansion: 'Perfect Order',
      number: '110/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Susumu Maeya',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Lumiose City',
      id: 'POR111',
      expansion: 'Perfect Order',
      number: '111/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Stadium',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'MARINA Chikazawa',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Naveen',
      id: 'POR112',
      expansion: 'Perfect Order',
      number: '112/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'DOM',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Poké Pad',
      id: 'POR113',
      expansion: 'Perfect Order',
      number: '113/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Studio Bora Inc.',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Rosa\'s Encouragement',
      id: 'POR114',
      expansion: 'Perfect Order',
      number: '114/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Atsushi Furusawa',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Sacred Ash',
      id: 'POR115',
      expansion: 'Perfect Order',
      number: '115/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Toyste Beach',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Tarragon',
      id: 'POR116',
      expansion: 'Perfect Order',
      number: '116/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Akira Komayama',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Wonderous Patch',
      id: 'POR117',
      expansion: 'Perfect Order',
      number: '117/088',
      rarity: `${emojis.UR} Ultra Rare`,
      hp: null,
      type: 'Item',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Studio Bora Inc.',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Mega Starmie ex',
      id: 'POR118',
      expansion: 'Perfect Order',
      number: '118/088',
      rarity: `${emojis.SIR} Special Illustration Rare`,
      hp: 330,
      type: emojis.water,
      stage: 'Stage 1',
      evolvesFrom: 'Staryu',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.lightning} × 2`,
      resistance: null,
      illustrators: 'takuyoa',
      pokedex: '0121',
      retreat: 2,
    },
    {
      name: 'Mega Clefable ex',
      id: 'POR119',
      expansion: 'Perfect Order',
      number: '119/088',
      rarity: `${emojis.SIR} Special Illustration Rare`,
      hp: 320,
      type: emojis.psychic,
      stage: 'Stage 1',
      evolvesFrom: 'Clefairy',
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.metal} × 2`,
      resistance: null,
      illustrators: 'Cona Nitanda',
      pokedex: '0036',
      retreat: 1,
    },
    {
      name: 'Mega Zygarde ex',
      id: 'POR120',
      expansion: 'Perfect Order',
      number: '120/088',
      rarity: `${emojis.SIR} Special Illustration Rare`,
      hp: 310,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'kantaro',
      pokedex: '0718',
      retreat: 2,
    },
    {
      name: 'Meowth ex',
      id: 'POR121',
      expansion: 'Perfect Order',
      number: '121/088',
      rarity: `${emojis.SIR} Special Illustration Rare`,
      hp: 170,
      type: emojis.colorless,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.fighting} × 2`,
      resistance: null,
      illustrators: 'Natsumi Yoshida',
      pokedex: '0052',
      retreat: 1,
    },
    {
      name: 'Jacinthe',
      id: 'POR122',
      expansion: 'Perfect Order',
      number: '122/088',
      rarity: `${emojis.SIR} Special Illustration Rare`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Souchirou Gunjima',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Rosa\'s Encouragement',
      id: 'POR123',
      expansion: 'Perfect Order',
      number: '123/088',
      rarity: `${emojis.CC} Special Illustration Rare`,
      hp: null,
      type: 'Supporter',
      stage: null,
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: null,
      resistance: null,
      illustrators: 'Iori Suzuki',
      pokedex: null,
      retreat: null,
    },
    {
      name: 'Mega Zygarde ex',
      id: 'POR124',
      expansion: 'Perfect Order',
      number: '124/088',
      rarity: `${emojis.MHR} Mega Hyper Rare`,
      hp: 310,
      type: emojis.fighting,
      stage: 'Basic',
      evolvesFrom: null,
      blurb: null,
      regulation: 'J',
      weakness: `${emojis.grass} × 2`,
      resistance: null,
      illustrators: 'takuyoa',
      pokedex: '0718',
      retreat: 2,
    },
  ], {
    ignoreDuplicates: true,
  });
  console.log(`[${chalk.green('INFO')}]  POR seeded.`);
}
